//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PVCR.DragDropExample.CloseWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="labware_weblims_close", ConfigurationName="CloseWS.labware_weblims_closePortType")]
    public interface labware_weblims_closePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:close", ReplyAction="urn:closeResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool close(string authToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:close", ReplyAction="urn:closeResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> closeAsync(string authToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface labware_weblims_closePortTypeChannel : PVCR.DragDropExample.CloseWS.labware_weblims_closePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class labware_weblims_closePortTypeClient : System.ServiceModel.ClientBase<PVCR.DragDropExample.CloseWS.labware_weblims_closePortType>, PVCR.DragDropExample.CloseWS.labware_weblims_closePortType {
        
        public labware_weblims_closePortTypeClient() {
        }
        
        public labware_weblims_closePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public labware_weblims_closePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public labware_weblims_closePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public labware_weblims_closePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool close(string authToken) {
            return base.Channel.close(authToken);
        }
        
        public System.Threading.Tasks.Task<bool> closeAsync(string authToken) {
            return base.Channel.closeAsync(authToken);
        }
    }
}
